name: 'GitHub Action for GraalVM'
description: 'Set up a specific version of GraalVM Community Edition'
author: 'GraalVM Developers'
branding:
  icon: 'terminal'  
  color: 'blue'
inputs:
  version:
    required: true
    description: 'GraalVM version (release, latest, dev).'
  java-version:
    required: true
    description: 'Java version (11 or 17, 8 or 16 for older releases).'
  components:
    required: false
    description: 'Comma-separated list of GraalVM components to be installed.'
    default: ''
  github-token:
    required: false
    description: 'Set it to secrets.GITHUB_TOKEN to increase rate limits when accessing the GitHub API.'
    default: ''
  set-java-home:
    required: false
    description: 'Set $JAVA_HOME to the GraalVM installation. Default: true.'
    default: 'true'
  native-image-musl:
    required: false
    description: 'Set up musl for static image building with GraalVM Native Image.'
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
